# Tarea: Ensamble y Clustering
---

1 de Diciembre de 2016

In [232]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn import tree

from sklearn.cross_validation import train_test_split
from sklearn import preprocessing, svm
from sklearn.metrics import confusion_matrix
import sklearn.metrics as mtrcs

import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pda
import numpy as np

In [233]:
link = "http://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"
abalone = pda.read_table(link, sep=',', header=None)
abalone.head()

0      1      2      3       4       5       6      7   8
0  M  0.455  0.365  0.095  0.5140  0.2245  0.1010  0.150  15
1  M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.070   7
2  F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.210   9
3  M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.155  10
4  I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.055   7

In [234]:
x1 = abalone[abalone.columns[1:]]
y1 = abalone[abalone.columns[0]]

In [235]:
y1num = pda.Categorical.from_array(y1).codes

In [236]:
print y1num.shape
print y1.shape

(4177,)
(4177,)


In [237]:
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1num, train_size=0.75)

In [238]:
x1_train.head()

1      2      3       4       5       6       7   8
2714  0.290  0.215  0.065  0.0985  0.0425  0.0210  0.0310   5
3523  0.260  0.205  0.070  0.0970  0.0415  0.0190  0.0305   4
700   0.385  0.285  0.105  0.2905  0.1215  0.0685  0.0875  12
4134  0.595  0.455  0.140  0.9140  0.3895  0.2225  0.2710   9
453   0.565  0.490  0.155  0.9245  0.4050  0.2195  0.2550  11

### 1. Decision Tree Classifier, Random Forest y Adaboost

### Arboles de clasificación

In [227]:
def arboles(x1_train, y1_train, x1_test, y1_test):
    treeclf = tree.DecisionTreeClassifier()
    treeclf.fit(x1_train, y1_train)
    fit_tree_train = treeclf.predict(x1_train)
    fit_tree_test = treeclf.predict(x1_test)

    print 'Accuracy train ', mtrcs.accuracy_score(y1_train, fit_tree_train)
    print confusion_matrix(y1_train, fit_tree_train)

    print 'Accuracy test ', mtrcs.accuracy_score(y1_test, fit_tree_test)
    print confusion_matrix(y1_test, fit_tree_test)
    
    return treeclf

In [228]:
tree0 = arboles(x1_train = x1_train, y1_train = y1_train == 0, 
        x1_test = x1_test, y1_test = y1_test == 0)

Accuracy train  1.0
[[2124    0]
 [   0 1008]]
Accuracy test  0.634449760766
[[529 217]
 [165 134]]


In [229]:
tree1 = arboles(x1_train = x1_train, y1_train = y1_train == 1, 
        x1_test = x1_test, y1_test = y1_test == 1)

Accuracy train  1.0
[[2141    0]
 [   0  991]]
Accuracy test  0.768421052632
[[581 113]
 [129 222]]


In [230]:
tree2 = arboles(x1_train = x1_train, y1_train = y1_train == 2, 
        x1_test = x1_test, y1_test = y1_test == 2)

Accuracy train  1.0
[[1999    0]
 [   0 1133]]
Accuracy test  0.594258373206
[[438 212]
 [212 183]]


In [231]:
tree3 = arboles(x1_train = x1_train, y1_train = y1_train, 
        x1_test = x1_test, y1_test = y1_test)

Accuracy train  1.0
[[1008    0    0]
 [   0  991    0]
 [   0    0 1133]]
Accuracy test  0.490909090909
[[122  42 135]
 [ 57 213  81]
 [150  67 178]]


### Random Forest

In [162]:
def bosque(x1_train, y1_train, x1_test, y1_test):
    randf = RandomForestClassifier()
    randf.fit(x1_train, y1_train)
    fit_randf_test = randf.predict(x1_test)
    fit_randf_train = randf.predict(x1_train)
    
    print 'Accuracy train', mtrcs.accuracy_score(y1_train, fit_randf_train)
    print confusion_matrix(y1_train, fit_randf_train)
    
    print 'Accuracy test', mtrcs.accuracy_score(y1_test, fit_randf_test)
    print confusion_matrix(y1_test, fit_randf_test)
    
    return randf

In [151]:
randf0 = bosque(x1_train = x1_train, y1_train = y1_train == 0, 
        x1_test = x1_test, y1_test = y1_test == 0)

Accuracy train 0.982439335888
[[2135    3]
 [  52  942]]
Accuracy test 0.687081339713
[[636  96]
 [231  82]]


In [150]:
randf1 = bosque(x1_train = x1_train, y1_train = y1_train == 1, 
        x1_test = x1_test, y1_test = y1_test == 1)

Accuracy train 0.984674329502
[[2119    8]
 [  40  965]]
Accuracy test 0.811483253589
[[644  64]
 [133 204]]


In [153]:
randf2 = bosque(x1_train = x1_train, y1_train = y1_train == 2, 
        x1_test = x1_test, y1_test = y1_test == 2)

Accuracy train 0.978927203065
[[1993    6]
 [  60 1073]]
Accuracy test 0.623923444976
[[523 127]
 [266 129]]


In [192]:
randf3 = bosque(x1_train = x1_train, y1_train = y1_train, 
        x1_test = x1_test, y1_test = y1_test)

Accuracy train 0.980842911877
[[ 982    5    7]
 [   6  994    5]
 [  26   11 1096]]
Accuracy test 0.512918660287
[[138  41 134]
 [ 43 237  57]
 [162  72 161]]


### Ada boosting

In [193]:
bdt = AdaBoostClassifier(DecisionTreeClassifier(), n_estimators=10)
bdt.fit(x1_train, y1_train)
fit_bdt_train = bdt.predict(x1_train)
confusion_matrix(y1_train, fit_bdt_train)

array([[ 994,    0,    0],
       [   0, 1005,    0],
       [   0,    0, 1133]])

In [194]:
fit_bdt_test = bdt.predict(x1_test)
print 'Accuracy ', mtrcs.accuracy_score(y1_test, fit_bdt_test)
confusion_matrix(y1_test, fit_bdt_test)

Accuracy  0.495693779904


array([[129,  47, 137],
       [ 60, 204,  73],
       [140,  70, 185]])

### 2. Kmeans

In [239]:
abalone.head()

0      1      2      3       4       5       6      7   8
0  M  0.455  0.365  0.095  0.5140  0.2245  0.1010  0.150  15
1  M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.070   7
2  F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.210   9
3  M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.155  10
4  I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.055   7

In [215]:
kmeans = KMeans(n_clusters=3, n_init = 10 )
kmeans.fit(x1_train)
kmeans.cluster_centers_

array([[  0.57176246,   0.44719062,   0.15309971,   0.99602757,
          0.43750499,   0.21886921,   0.28186452,  10.43753666],
       [  0.58981233,   0.4674933 ,   0.1680563 ,   1.14015952,
          0.43202815,   0.24227748,   0.36399196,  16.36461126],
       [  0.42225806,   0.32248102,   0.10716319,   0.43655693,
          0.1994222 ,   0.09435863,   0.12251328,   6.88804554]])

In [1]:
fit_km_train = kmeans.predict(x1_train)
fit_km_test = kmeans.predict(x1_test)

NameError: name 'kmeans' is not defined

In [243]:
fit_km_train = kmeans.predict(x1_train)
fit_km_test = kmeans.predict(x1_test)
print 'Accuracy train ', mtrcs.accuracy_score(y1_train, fit_km_train)
print confusion_matrix(y1_train, fit_km_train)
print 'Accuracy test ', mtrcs.accuracy_score(y1_test, fit_km_test)
print confusion_matrix(y1_test, fit_km_test)

Accuracy train  0.295019157088
[[676 167 144]
 [273  40 693]
 [753 178 208]]
Accuracy test  0.311004784689
[[226  52  42]
 [ 99   8 229]
 [253  45  91]]


In [241]:
trclf = tree.DecisionTreeClassifier()
trclf0 = trclf.fit(x1_train, fit_km_train == 0)

fit_trclf0_train = trclf0.predict(x1_train)
fit_trclf0_test = trclf0.predict(x1_test)

print 'Accuracy ', mtrcs.accuracy_score(fit_km_train == 0, fit_trclf0_train)
print confusion_matrix(fit_km_train == 0, fit_trclf0_train)
print 'Accuracy ', mtrcs.accuracy_score(fit_km_test == 0, fit_trclf0_test)
print confusion_matrix(fit_km_test == 0, fit_trclf0_test)

Accuracy  1.0
[[1430    0]
 [   0 1702]]
Accuracy  1.0
[[467   0]
 [  0 578]]


In [242]:
randclf = RandomForestClassifier()
randclf = randclf.fit(x1_train, fit_km_train == 0)

fit_randclf_train = randclf.predict(x1_train)
fit_randclf_test = randclf.predict(x1_test)

print 'Accuracy ', mtrcs.accuracy_score(fit_km_train == 0, fit_randclf_train)
print confusion_matrix(fit_km_train == 0, fit_randclf_train)
print 'Accuracy ', mtrcs.accuracy_score(fit_km_test == 0, fit_randclf_test)
print confusion_matrix(fit_km_test == 0, fit_randclf_test)

Accuracy  1.0
[[1430    0]
 [   0 1702]]
Accuracy  0.999043062201
[[467   0]
 [  1 577]]
